version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: RMIPSS_System/Dockerfile
    container_name: RMIPSS-WEB-APP
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=RMIPSS;Username=root;Password=root
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: RMIPSS
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data: